### ISSUE TITLE
KDE Plasma does not start when reusing user@<uid>.service

### ISSUE THREAD

**Issue by hexchain** [bus1/dbus-broker#205] opened 2019-06-26 12:14 UTC
I'm using dbus-broker on Arch Linux with SDDM and KDE.

By default, `logind` keeps user service (`user@<uid>.service`) for 10s after the user logging out, in an attempt to speed up logout/login cycles. However, with dbus-broker as session bus, Plasma does not start (stuck at splash screen because some KDE daemons cannot start) if there is a running user service.

Things I've tried:
1. Set `UserStopDelaySec=infinity` in `/etc/systemd/logind.conf`.
2. Use either dbus-broker or dbus-daemon as the system bus (does not seem to matter at all).
3. Manually enable dbus-broker or dbus-daemon as session bus, then try to log out and log in.

Every time when dbus-broker is the session bus, kglobalaccel5 refuses to start:
```
Jun 26 13:14:18 x kglobalaccel5[14237]: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
                                        Available platform plugins are: wayland-org.kde.kwin.qpa, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
Jun 26 13:15:06 x kactivitymanagerd[14382]: Couldn't start kglobalaccel from org.kde.kglobalaccel.service: QDBusError("org.freedesktop.DBus.Error.NoReply", "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.")
```

This might not be a dbus-broker problem as one of my friends cannot seem to reproduce it.

**Comment by teg** [comment] 2019-07-19 11:21
Could you check `journalctl -u dbus-btoker`? It may be that you have some at_console policy that is messing up?

**Comment by hexchain** [comment] 2019-07-25 03:19
`journalctl -u dbus-broker`:

```
-- Logs begin at Sat 2019-06-29 22:13:25 CST, end at Thu 2019-07-25 11:16:11 CST. --
Jul 25 11:04:41 x systemd[1]: Starting D-Bus System Message Bus...
Jul 25 11:04:41 x systemd[1]: Started D-Bus System Message Bus.
Jul 25 11:04:41 x dbus-broker-launch[514]: Deprecated policy context in /usr/share/dbus-1/system.d/bluetooth.conf +24. The 'at_console' context is deprecated and will be ignored in the future.
Jul 25 11:04:41 x dbus-broker-launch[514]: Deprecated policy context in /usr/share/dbus-1/system.d/com.redhat.NewPrinterNotification.conf +5. The 'at_console' context is deprecated and will be ignored in the future.
Jul 25 11:04:41 x dbus-broker-launch[514]: Deprecated policy context in /usr/share/dbus-1/system.d/com.redhat.PrinterDriversInstaller.conf +5. The 'at_console' context is deprecated and will be ignored in the future.
Jul 25 11:04:41 x dbus-broker-lau[514]: Ready
Jul 25 11:04:54 x dbus-broker-launch[514]: Activation request for 'org.freedesktop.Avahi' failed: The systemd unit 'dbus-org.freedesktop.Avahi.service' could not be found.
Jul 25 11:04:54 x dbus-broker-launch[514]: Activation request for 'org.freedesktop.ModemManager1' failed: The systemd unit 'dbus-org.freedesktop.ModemManager1.service' could not be found.
```

`journalctl -u dbus-broker --user`:

```
-- Logs begin at Sat 2019-06-29 22:16:51 CST, end at Thu 2019-07-25 11:14:36 CST. --
Jul 25 11:04:50 x systemd[1324]: Starting D-Bus User Message Bus...
Jul 25 11:04:50 x dbus-broker-launch[1359]: Service file '/usr/share/dbus-1/services/org.jackaudio.service' is not named after the D-Bus name 'org.jackaudio.service'.
Jul 25 11:04:50 x dbus-broker-launch[1359]: Service file '/usr/share/dbus-1/services/org.kde.kscreen.service' is not named after the D-Bus name 'org.kde.KScreen'.
Jul 25 11:04:50 x dbus-broker-launch[1359]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Jul 25 11:04:50 x dbus-broker-launch[1359]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Jul 25 11:04:50 x dbus-broker-launch[1359]: Service file '/usr/share/dbus-1/services/org.kde.plasma.Notifications.service' is not named after the D-Bus name 'org.freedesktop.Notifications'.
Jul 25 11:04:50 x dbus-broker-launch[1359]: Service file '/usr/share/dbus-1/services/org.kde.baloorunner.service' is not named after the D-Bus name 'org.kde.runners.baloo'.
Jul 25 11:04:50 x dbus-broker-launch[1359]: Service file '/usr/share/dbus-1/services/org.kde.activitymanager.service' is not named after the D-Bus name 'org.kde.ActivityManager'.
Jul 25 11:04:50 x dbus-broker-launch[1359]: Service file '/usr/share/dbus-1/services/org.kde.dolphin.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'.
Jul 25 11:04:50 x dbus-broker-launch[1359]: Service file '/usr/share/dbus-1/services/org.gnome.FileRoller.ArchiveManager1.service' is not named after the D-Bus name 'org.gnome.ArchiveManager1'.
Jul 25 11:04:50 x systemd[1324]: Started D-Bus User Message Bus.
Jul 25 11:04:50 x dbus-broker-lau[1359]: Ready
Jul 25 11:09:51 x dbus-broker[1360]: Dispatched 4371 messages @ 7(±13)μs / message.
Jul 25 11:09:51 x systemd[1324]: Stopping D-Bus User Message Bus...
Jul 25 11:09:51 x systemd[1324]: dbus-broker.service: Succeeded.
Jul 25 11:09:51 x systemd[1324]: Stopped D-Bus User Message Bus.
Jul 25 11:12:37 x systemd[2520]: Starting D-Bus User Message Bus...
Jul 25 11:12:37 x dbus-broker-launch[2558]: Service file '/usr/share/dbus-1/services/org.jackaudio.service' is not named after the D-Bus name 'org.jackaudio.service'.
Jul 25 11:12:37 x dbus-broker-launch[2558]: Service file '/usr/share/dbus-1/services/org.kde.kscreen.service' is not named after the D-Bus name 'org.kde.KScreen'.
Jul 25 11:12:37 x dbus-broker-launch[2558]: Service file '/usr/share/dbus-1/services/org.kde.plasma.Notifications.service' is not named after the D-Bus name 'org.freedesktop.Notifications'.
Jul 25 11:12:37 x dbus-broker-launch[2558]: Service file '/usr/share/dbus-1/services/org.kde.baloorunner.service' is not named after the D-Bus name 'org.kde.runners.baloo'.
Jul 25 11:12:37 x dbus-broker-launch[2558]: Service file '/usr/share/dbus-1/services/org.kde.activitymanager.service' is not named after the D-Bus name 'org.kde.ActivityManager'.
Jul 25 11:12:37 x dbus-broker-launch[2558]: Service file '/usr/share/dbus-1/services/org.kde.dolphin.FileManager1.service' is not named after the D-Bus name 'org.freedesktop.FileManager1'.
Jul 25 11:12:37 x dbus-broker-launch[2558]: Service file '/usr/share/dbus-1/services/org.gnome.FileRoller.ArchiveManager1.service' is not named after the D-Bus name 'org.gnome.ArchiveManager1'.
Jul 25 11:12:37 x dbus-broker-launch[2558]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated and ignored
Jul 25 11:12:37 x dbus-broker-launch[2558]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated and ignored
Jul 25 11:12:37 x systemd[2520]: Started D-Bus User Message Bus.
Jul 25 11:12:37 x dbus-broker-lau[2558]: Ready
```

**Comment by teg** [comment] 2019-07-25 12:15
Hm, ok, that did not show any problems. If there had been a security denial there should be a log-line about it. The reason for the error could then either be that the remote side never answered and disconnected (so the error will be sent out from the broker), or the remote side is still there but it hasn't answered (in which case your library could have an internal timeout genereting the error).

Trying to monitor with "busctl monitor" could give you more info about exactly which app is sending what message and whether or not the remote side is disconnecting/answering.

**Comment by Maryse47** [comment] 2019-08-09 09:59
I believe I had same issue with re-login in KDE session and found that I can't do it when some user processes are still running from old session. It only works when I wait until they timeout. The solution may be to set `UserStopDelaySec=0` then.

**Comment by dvdhrm** [comment] 2020-02-06 14:52
Can anyone still reproduce this as of today?

**Comment by hexchain** [comment] 2020-02-08 14:24
I can't seem to reproduce this anymore.
```
systemd 244.2-1
dbus 1.12.16-5
dbus-broker 21-2
```

**Comment by dvdhrm** [comment] 2020-02-10 13:57
Thanks a lot for confirming! I will go ahead and close this, as I cannot reproduce it either. If the issue is coming up again, please let me know so I will gladly look into this again.

**Closed by dvdhrm** 2020-02-10 13:57 UTC
