### ISSUE TITLE
fails to boot

### ISSUE THREAD

**Issue by sheepdestroyer** [bus1/dbus-broker#21] opened 2017-08-23 22:12 UTC
v3 installed by copr repo fails to boot my fedora 26 on a thinkpad x220

**Comment by teg** [comment] 2017-08-23 22:59
With or without selinux enabled? Could you attach the relevant journal
output (just grep for dbus-broker).?

**Comment by sheepdestroyer** [comment] 2017-08-24 11:55
selinux was active; i'll copy the journal output when back home

**Comment by chdongsh** [comment] 2017-08-24 13:14
I also compiled dbus-broker from git, but it can't boot into fedora rawhide on my clevo P750zm. and I got two timeout errors when making test.
[testlog.txt](https://github.com/bus1/dbus-broker/files/1248898/testlog.txt)

**Comment by sheepdestroyer** [comment] 2017-08-24 21:24
I think that is the corresponding log : 
```
Aug 23 23:58:53 sheepora-X220 systemd[1]: Started CUPS Scheduler.
Aug 23 23:58:53 sheepora-X220 audit[1]: AVC avc:  denied  { create } for  pid=1 comm="systemd" scontext=system_u:system_r:init_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=unix_stream_socket permissive=0
Aug 23 23:58:53 sheepora-X220 systemd[1]: Reached target Paths.
Aug 23 23:58:53 sheepora-X220 systemd[1]: dbus.socket: Failed to listen on sockets: Permission denied
Aug 23 23:58:53 sheepora-X220 systemd[1]: Failed to listen on D-Bus System Message Bus Socket.
Aug 23 23:58:53 sheepora-X220 systemd[1]: Dependency failed for Switcheroo Control Proxy service.
Aug 2¨¨
3 23:58:53 sheepora-X220 systemd[1]: switcheroo-control.service: Job switcheroo-control.service/start failed with result 'dependency'.
Aug 23 23:58:53 sheepora-X220 systemd[1]: Dependency failed for firewalld - dynamic firewall daemon.
```

**Comment by dvdhrm** [comment] 2017-08-25 14:24
This is a duplicate of #29 and discussed there. I will close this report. Please continue discussion there.

Current status: If this was due to using the dbus-broker-git packages, please try again with master of today, since it contains an selinux-relabeling fix.

**Closed by dvdhrm** 2017-08-25 14:24 UTC
