### ISSUE TITLE
dbus-broker-launch fails to start if there are multiple service files providing the same dbus name

### ISSUE THREAD

**Issue by mbiebl** [bus1/dbus-broker#38] opened 2017-08-28 01:04 UTC
On this particular test system, I have both KDE and GNOME installed.
When trying to run ```systemctl --user start dbus-broker.service``` I get:
```
Aug 28 02:47:34 pluto systemd[1961]: Started D-Bus User Message Bus.
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Listening on inherited socket
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gtk.vfs.Metadata.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Epiphany.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Weather.BackgroundService.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.kde.kdesvnd.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Software.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.kde.kscreen.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.kde.dolphin.FileManager1.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.taquin.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.kde.kssld5.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.Telepathy.Client.Vino.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.zeitgeist.Engine.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gtk.vfs.GoaVolumeMonitor.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Documents.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gtk.vfs.AfcVolumeMonitor.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Dictionary.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.ColorHelper.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.hexchat.service.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Sushi.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.kde.knotify.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.impl.portal.desktop.gtk.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.systemd1.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Todo.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/ca.desrt.dconf-editor.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Rhythmbox3.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.fedoraproject.Config.Printing.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.Tracker1.Writeback.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Contacts.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.portal.Desktop.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.Calendar.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.ControlCenter.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gtk.vfs.MTPVolumeMonitor.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gtk.vfs.Daemon.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.impl.portal.PermissionStore.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.kde.fontinst.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Cheese.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.keyring.SystemPrompter.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.GConf.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.a11y.Bus.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.kde.kwalletd5.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Calculator.SearchProvider.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Photos.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.knopwob.dunst.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Rygel1.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Logs.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.Tracker1.Miner.Userguides.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.OnlineMiners.Facebook.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Weather.Application.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.keyring.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Shell.PortalHelper.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.kde.kglobalaccel.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.seahorse.Application.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/us.kirkland.terminals.byobu.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Characters.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.Totem.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.evince.Daemon.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.Flatpak.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/com.gexperts.Tilix.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/com.intel.dleyna-server.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.Telepathy.Client.Logger.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.seahorse.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.gedit.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.evolution.dataserver.Sources.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.Tracker1.Miner.Files.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.gnome.OnlineAccounts.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Loading service '/usr/share/dbus-1/services/org.freedesktop.FileManager1.service'
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: ERROR manager_load_service @ ../src/launch/main.c +653: Input/output error
Aug 28 02:47:34 pluto dbus-broker-launch[1988]:       manager_load_services @ ../src/launch/main.c +714
Aug 28 02:47:34 pluto dbus-broker-launch[1988]:       manager_run @ ../src/launch/main.c +856
Aug 28 02:47:34 pluto dbus-broker-launch[1988]:       run @ ../src/launch/main.c +1021
Aug 28 02:47:34 pluto dbus-broker-launch[1988]:       main @ ../src/launch/main.c +1054
Aug 28 02:47:34 pluto dbus-broker-launch[1988]: Exiting due to fatal error: -5
Aug 28 02:47:59 pluto systemd[1961]: dbus-broker.service: Main process exited, code=exited, status=1/FAILURE
Aug 28 02:47:59 pluto systemd[1961]: dbus-broker.service: Unit entered failed state.
```

The problem afaics is this:
```
$ grep FileManager /usr/share/dbus-1/services/*.service
/usr/share/dbus-1/services/org.freedesktop.FileManager1.service:Name=org.freedesktop.FileManager1
/usr/share/dbus-1/services/org.kde.dolphin.FileManager1.service:Name=org.freedesktop.FileManager1
```
I.e. I have two service files providing the same D-Bus name.
The spec is not totally clear in that regard. Afaik, dbus (the reference implementation) basically picks one of the service files at random.
dbus-broker-launch should handle this more gracefully. Maybe log an error message about this and either pick one (at random) or ignore all service files which provide/claim the same name.

**Comment by teg** [comment] 2017-08-28 08:15
Thanks for the report!

**Comment by teg** [comment] 2017-08-29 11:16
This should now be fixed in master.

**Closed by teg** 2017-08-29 11:16 UTC

**Comment by mbiebl** [comment] 2017-08-29 21:02
I can confirm that dbus-broker-launch works fine now. Thanks for the prompt fix!

**Comment by smcv** [comment] 2017-08-30 14:01
See also https://bugs.freedesktop.org/show_bug.cgi?id=99873 https://bugs.freedesktop.org/show_bug.cgi?id=99874 and https://bugs.freedesktop.org/show_bug.cgi?id=99876 for which patches would be welcome. There is a bit more context in those bugs.

**Comment by teg** [comment] 2017-08-30 14:11
@smcv thanks for the pointers. Worth noting that currently we differ from the reference implementation in that we use the same service file (the first in readdir() order) regardless of activation being done based on SystemdService or not.

**Comment by smcv** [comment] 2017-08-30 16:52
When I say canonically-named service file I mean `${search_path_entry}/${name}.service` containing `Name=${name}`.

> Worth noting that currently we differ from the reference implementation in that we use the same service file (the first in readdir() order) regardless of activation being done based on SystemdService or not.

That's an accident of how systemd activation was implemented, tbh.

Please note that the rules are different for system and session services. In dbus-daemon, the discriminator is actually whether activation uses the setuid helper or not (if it does, then it must be the system bus, whose search path gets hard-coded into the setuid helper to harden it against abuse), because there is nothing hard-coded into dbus-daemon that cares about system vs. session vs. other buses apart from a bit of logging.

For **system** services, the intention was to always activate from the file with the canonical name (see `doc/system-activation.txt` for the original design). I would prefer a new implementation like dbus-broker to skip ahead to only being willing to activate system services that are canonically-named (effectively, fixing fd.o 99874 before dbus-daemon does). I consider it to be a bug that dbus-daemon is ever willing to activate non-canonically-named **system** services, and I'll fix it when I have time, perhaps even before 1.12.0.

For **session** services, the intended behaviour of the current dbus-daemon appears to be an arbitrary order (as currently implemented it's readdir() order, but I don't consider that to be a guarantee). I don't think fixing fd.o 99876 would violate any intentionally-made guarantees (the canonically-named file is surely just as good an arbitrary choice as the first in readdir() order), and it might be worthwhile for dbus-broker to skip ahead to the fixed state before dbus-daemon does.

For session services where there is no canonically-named service file, in the very long term it might even be worthwhile to ignore non-canonically-named files (or at least have a config option to do so). However, that is an incompatible change that should not be made lightly - fd.o 99873 has a list of some packages that would be broken by that change.
