### ISSUE TITLE
dbus-broker fails to start with kernel 5.1-rc3

### ISSUE THREAD

**Issue by Maryse47** [bus1/dbus-broker#198] opened 2019-04-06 14:46 UTC
```
systemd[1]: Starting D-Bus System Message Bus...
systemd[1]: Started D-Bus System Message Bus.
dbus-broker-launch[1047]: ERROR bus_apparmor_is_enabled @ ../dbus-broker/src/util/apparmor.c +49: Input/output error
dbus-broker-launch[1047]:       manager_run @ ../dbus-broker/src/launch/main.c +1655
dbus-broker-launch[1047]:       run @ ../dbus-broker/src/launch/main.c +1857
dbus-broker-launch[1047]:       main @ ../dbus-broker/src/launch/main.c +1886
dbus-broker-launch[1047]: Exiting due to fatal error: -5
systemd[1]: dbus-broker.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: dbus-broker.service: Failed with result 'exit-code'.
systemd[1]: Starting D-Bus System Message Bus...
systemd[1]: Started D-Bus System Message Bus.
dbus-broker-launch[1081]: ERROR bus_apparmor_is_enabled @ ../dbus-broker/src/util/apparmor.c +49: Input/output error
dbus-broker-launch[1081]:       manager_run @ ../dbus-broker/src/launch/main.c +1655
dbus-broker-launch[1081]:       run @ ../dbus-broker/src/launch/main.c +1857
dbus-broker-launch[1081]:       main @ ../dbus-broker/src/launch/main.c +1886
dbus-broker-launch[1081]: Exiting due to fatal error: -5
```

Kernel config:
```
CONFIG_SECURITY_SELINUX=y
CONFIG_SECURITY_SELINUX_BOOTPARAM=y
# CONFIG_SECURITY_SELINUX_DISABLE is not set
CONFIG_SECURITY_SELINUX_DEVELOP=y
CONFIG_SECURITY_SELINUX_AVC_STATS=y
# CONFIG_SECURITY_SMACK is not set
# CONFIG_SECURITY_TOMOYO is not set
CONFIG_SECURITY_APPARMOR=y
CONFIG_SECURITY_APPARMOR_HASH=y
CONFIG_SECURITY_APPARMOR_HASH_DEFAULT=y
# CONFIG_SECURITY_APPARMOR_DEBUG is not set
# CONFIG_SECURITY_LOADPIN is not set
CONFIG_SECURITY_YAMA=y
CONFIG_SECURITY_SAFESETID=y
CONFIG_INTEGRITY=y
# CONFIG_INTEGRITY_SIGNATURE is not set
CONFIG_INTEGRITY_AUDIT=y
# CONFIG_IMA is not set
# CONFIG_EVM is not set
# CONFIG_DEFAULT_SECURITY_SELINUX is not set
CONFIG_DEFAULT_SECURITY_APPARMOR=y
# CONFIG_DEFAULT_SECURITY_DAC is not set
CONFIG_LSM="yama,loadpin,safesetid,integrity,apparmor,selinux,smack,tomoyo"
```

**Comment by dvdhrm** [comment] 2019-04-08 07:25
This looks like a kernel regression. I reported this upstream. I think the culprit is this kernel change:

```
commit c5459b829b716dafd226ad270f25c9a3050f7586
Author: Kees Cook <keescook@chromium.org>
Date:   Thu Sep 13 22:28:48 2018 -0700

    LSM: Plumb visibility into optional "enabled" state
```

dbus-broker can be adjusted to allow for this, but I am a bit reluctant to push a fix if upstream is going to revert the AppArmor changes, anyway. I will wait for a response form upstream. In the meantime, this should make dbus-broker boot with 5.1-rc3:

```
 % git diff
diff --git a/src/util/apparmor.c b/src/util/apparmor.c
index 8892b7a..c3fc664 100644
--- a/src/util/apparmor.c
+++ b/src/util/apparmor.c
@@ -40,9 +40,11 @@ int bus_apparmor_is_enabled(bool *enabledp) {
 
                 switch (buffer[0]) {
                         case 'Y':
+                        case '1':
                                 enabled = true;
                                 break;
                         case 'N':
+                        case '0':
                                 enabled = false;
                                 break;
                         default:
```

**Comment by Maryse47** [comment] 2019-04-08 10:57
@dvdhrm could you link your report to upstream?

**Comment by dvdhrm** [comment] 2019-04-08 11:40
@Maryse47 Well, it is on a mailing-list so I cannot really link to it, but you can track the messages via your mail-archive of choice. My initial report was: https://lore.kernel.org/lkml/CADyDSO6k8vYb1eryT4g6+EHrLCvb68GAbHVWuULkYjcZcYNhhw@mail.gmail.com/

**Comment by Maryse47** [comment] 2019-04-08 11:54
Link to mail archive is what I had in mind, thx.

**Comment by dvdhrm** [comment] 2019-04-08 16:17
Kees was so kind to provide a fix: https://lore.kernel.org/lkml/20190408160706.GA18786@beast/T/#u

I will test this tomorrow. Feel free to give it a spin if you know how.

**Comment by dvdhrm** [comment] 2019-04-10 19:15
This is now merged upstream [1]. I will close this now, but please feel free to re-open if any issues reappear!

Thanks a lot for the report!
David

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=e33c1b9923775d17ad246946fe67fcb9be288677

**Closed by dvdhrm** 2019-04-10 19:15 UTC
