### ISSUE TITLE
still can't boot fedora 26

### ISSUE THREAD

**Issue by sheepdestroyer** [bus1/dbus-broker#47] opened 2017-09-01 22:19 UTC
just built from master : 

````
Sep 01 23:37:11 sheepora-X220 auditd[609]: Error setting audit daemon pid (Invalid argument)
Sep 02 01:37:44 sheepora-X220 kernel: RAS: Correctable Errors collector initialized.
Sep 01 23:37:46 sheepora-X220 kernel: iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-6000-6.ucode failed with error -2
Sep 01 23:37:46 sheepora-X220 kernel: iwlwifi 0000:03:00.0: Direct firmware load for iwlwifi-6000-5.ucode failed with error -2
Sep 01 23:37:47 sheepora-X220 dbus-broker-launch[642]: Reply/Error policy in /usr/share/dbus-1/system.conf +56: Explicit policies on replies and error
s are deprecated and ignored
Sep 01 23:37:47 sheepora-X220 dbus-broker-launch[642]: Reply/Error policy in /usr/share/dbus-1/system.conf +57: Explicit policies on replies and error
s are deprecated and ignored
Sep 01 23:37:47 sheepora-X220 dbus-broker-launch[642]: Reply/Error policy in /usr/share/dbus-1/system.conf +61: Explicit policies on replies and error
s are deprecated and ignored
Sep 01 23:37:47 sheepora-X220 dbus-broker-launch[642]: Reply/Error policy in /usr/share/dbus-1/system.conf +62: Explicit policies on replies and error
s are deprecated and ignored
Sep 01 23:37:48 sheepora-X220 gdm[726]: GdmLocalDisplayFactory: Failed to issue method call: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Co
uld not activate remote peer.
Sep 01 23:37:48 sheepora-X220 libvirtd[719]: 2017-09-01 21:37:48.819+0000: 777: error : virNodeSuspendSupportsTarget:336 : internal error: Cannot probe for supported suspend types

````

**Comment by teg** [comment] 2017-10-17 14:42
Are you able to reproduce with current git?

**Comment by sheepdestroyer** [comment] 2017-10-18 14:25
I was waiting for an updated copr build to retry but neither stable nor git have been built for weeks.

I am on fedora 27 beta now ; if that's still relevant to you, I'll pull the current git qnd try.
Sorry not being able to test on fedora 26 anymore.

**Comment by sheepdestroyer** [comment] 2017-10-20 03:41
Could boot my upgraded to Fedora 27 system on last git

**Comment by dvdhrm** [comment] 2017-10-20 09:17
Yeah, we didn't trigger the copr builds, since the package is now in testing. The official spec file is located here:

http://src.fedoraproject.org/rpms/dbus-broker

I will close this bug, since at the time you reported it there were still many open issues, which now have been fixed. Feel free to reopen if issues remain.

Thanks a lot for reporting!

**Closed by dvdhrm** 2017-10-20 09:17 UTC
